//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class syco_trainingEntities1 : DbContext
    {
        public syco_trainingEntities1()
            : base("name=syco_trainingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sbCrewMember> sbCrewMember { get; set; }
        public virtual DbSet<sbTask> sbTask { get; set; }
        public virtual DbSet<sbType> sbType { get; set; }
    }
}
